- an_wo:
   mean: 0.03
   std: 0.03
   ratio: 0.10
- of_wo:
   mean: 0.02
   std: 0.02
- pp_wo:
   mean: 0.02
   std: 0.02
   scale: 1.5
- adv_wo:
   mean: 0.03
   std: 0.03
   scale: 1.5
- wh_wo:
   mean: 0.02
   std: 0.02
   loc: 1.5
   scale: 1.0
- norm_wo:
   mean: 0.3
   std: 0.3
   loc: 0.0
   scale: 0.5

