errant_source_path: ../errant/start.sh
bea19:
   valid_orig: ../corpora/bea19/eval/ABCN.dev.bea19.orig
   valid_src: ../data/abcn/bea_train_16000/valid.src
   test_src: ../data/abcn/bea_train_16000/test.src
   valid_m2: ../corpora/bea19/train/wi+locness/wi+locness/m2/ABCN.dev.gold.bea19.m2
conll:
   m2_scorer: ../m2score/m2scorer/m2scorer
   valid_src: ../data/conll/bea_train_16000/valid.src
   test_src: ../data/conll/bea_train_16000/test.src
   valid_m2: ../corpora/conll/conll13/release2.3.1/original/data/official-preprocessed.m2
   test_m2: ../corpora/conll/conll14/conll14st-test-data/noalt/official-2014.combined.m2
fce:
   valid_orig: ../data/fce/valid.src
   test_orig: ../data/fce/test.src
   valid_src: ../data/fce/bea_train_16000/valid.src
   test_src: ../data/fce/bea_train_16000/test.src
   valid_m2: ../corpora/bea19/train/fce/fce/m2/fce.dev.gold.bea19.m2
   test_m2: ../corpora/bea19/train/fce/fce/m2/fce.test.gold.bea19.m2
jfleg:
   gleu_scorer: ../corpora/jfleg/jfleg/eval/gleu.py
   valid_orig: ../corpora/jfleg/jfleg/dev/dev.src
   test_orig: ../corpora/jfleg/jfleg/test/test.src
   valid_src: ../data/jfleg/bea_train_16000/valid.src
   test_src: ../data/jfleg/bea_train_16000/test.src
   valid_ref:
      - ../corpora/jfleg/jfleg/dev/dev.ref0
      - ../corpora/jfleg/jfleg/dev/dev.ref1
      - ../corpora/jfleg/jfleg/dev/dev.ref2
      - ../corpora/jfleg/jfleg/dev/dev.ref3
   test_ref:
      - ../corpora/jfleg/jfleg/test/test.ref0
      - ../corpora/jfleg/jfleg/test/test.ref1
      - ../corpora/jfleg/jfleg/test/test.ref2
      - ../corpora/jfleg/jfleg/test/test.ref3
