- standard_prep:
   mean: 0.05
   std: 0.05
- prep_from:
   mean: 0.05
   std: 0.05
- prep_into:
   mean: 0.05
   std: 0.05
- prep_among:
   mean: 0.05
   std: 0.05
- prep_amongst:
   mean: 0.05
   std: 0.05
- prep_amid:
   mean: 0.05
   std: 0.05
- prep_amidst:
   mean: 0.05
   std: 0.05
- prep_about:
   mean: 0.05
   std: 0.05
- prep_against:
   mean: 0.05
   std: 0.05
- prep_by:
   mean: 0.05
   std: 0.05
- prep_since:
   mean: 0.05
   std: 0.05
- prep_until:
   mean: 0.05
   std: 0.05
- prep_till:
   mean: 0.05
   std: 0.05
- prep_between:
   mean: 0.05
   std: 0.05
- prep_during:
   mean: 0.05
   std: 0.05
- prep_within:
   mean: 0.05
   std: 0.05
- prep_after:
   mean: 0.05
   std: 0.05
- prep_before:
   mean: 0.05
   std: 0.05
- prep_as:
   mean: 0.05
   std: 0.05
- prep_like:
   mean: 0.05
   std: 0.05
- prep_than:
   mean: 0.05
   std: 0.05
- prep_through:
   mean: 0.05
   std: 0.05
- prep_throughout:
   mean: 0.05
   std: 0.05
- prep_above:
   mean: 0.05
   std: 0.05
- prep_behind:
   mean: 0.05
   std: 0.05
- prep_below:
   mean: 0.05
   std: 0.05
- prep_beyond:
   mean: 0.05
   std: 0.05
- prep_over:
   mean: 0.05
   std: 0.05
- prep_across:
   mean: 0.05
   std: 0.05
- prep_under:
   mean: 0.05
   std: 0.05
- prep_upon:
   mean: 0.05
   std: 0.05
- prep_out:
   mean: 0.05
   std: 0.05
- prep_toward:
   mean: 0.05
   std: 0.05
- standard_mark:
   mean: 0.05
   std: 0.05
- mark_for:
   mean: 0.05
   std: 0.05
- agent_by:
   mean: 0.05
   std: 0.05
- agent_between:
   mean: 0.05
   std: 0.05
- pcomp_of:
   mean: 0.05
   std: 0.05
- pcomp_to:
   mean: 0.05
   std: 0.05
- pcomp_on:
   mean: 0.05
   std: 0.05
- pcomp_for:
   mean: 0.05
   std: 0.05
- pcomp_at:
   mean: 0.05
   std: 0.05
- pcomp_by:
   mean: 0.05
   std: 0.05
- dative_to:
   mean: 0.05
   std: 0.05
- dative_for:
   mean: 0.05
   std: 0.05
- prep_advmod:
   mean: 0.05
   std: 0.05
- post_vb_prep:
   mean: 0.05
   std: 0.05
- 1sng_subj:
   mean: 0.03
   std: 0.03
- 1sng_nsubj_obj:
   mean: 0.03
   std: 0.03
- 1sng_dobj:
   mean: 0.03
   std: 0.03
- 1sng_pobj:
   mean: 0.03
   std: 0.03
- 1sng_dative:
   mean: 0.03
   std: 0.03
- 1sng_poss:
   mean: 0.03
   std: 0.03
- 1sng_poss_det:
   mean: 0.03
   std: 0.03
- 1sng_reflexive:
   mean: 0.03
   std: 0.03
- 1sng_appos_reflexive:
   mean: 0.03
   std: 0.03
- 1sng_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 1plu_subj:
   mean: 0.03
   std: 0.03
- 1plu_pobj:
   mean: 0.03
   std: 0.03
- 1plu_dobj:
   mean: 0.03
   std: 0.03
- 1plu_nsubj_obj:
   mean: 0.03
   std: 0.03
- 1plu_dative:
   mean: 0.03
   std: 0.03
- 1plu_poss:
   mean: 0.03
   std: 0.03
- 1plu_poss_det:
   mean: 0.03
   std: 0.03
- 1plu_reflexive:
   mean: 0.03
   std: 0.03
- 1plu_appos_reflexive:
   mean: 0.03
   std: 0.03
- 1plu_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 2nd_subj:
   mean: 0.03
   std: 0.03
- 2nd_pobj:
   mean: 0.03
   std: 0.03
- 2nd_dobj:
   mean: 0.03
   std: 0.03
- 2nd_dative:
   mean: 0.03
   std: 0.03
- 2nd_poss:
   mean: 0.03
   std: 0.03
- 2nd_poss_det:
   mean: 0.03
   std: 0.03
- 2sng_reflexive:
   mean: 0.03
   std: 0.03
- 2sng_appos_reflexive:
   mean: 0.03
   std: 0.03
- 2sng_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 2plu_reflexive:
   mean: 0.03
   std: 0.03
- 2plu_appos_reflexive:
   mean: 0.03
   std: 0.03
- 2plu_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_masc_subj:
   mean: 0.03
   std: 0.03
- 3sng_masc_pobj:
   mean: 0.03
   std: 0.03
- 3sng_masc_dobj:
   mean: 0.03
   std: 0.03
- 3sng_masc_nsubj_obj:
   mean: 0.03
   std: 0.03
- 3sng_masc_dative:
   mean: 0.03
   std: 0.03
- 3sng_masc_poss:
   mean: 0.03
   std: 0.03
- 3sng_masc_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_masc_appos_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_masc_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_fem_subj:
   mean: 0.03
   std: 0.03
- 3sng_fem_pobj:
   mean: 0.03
   std: 0.03
- 3sng_fem_dobj:
   mean: 0.03
   std: 0.03
- 3sng_fem_nsubj_obj:
   mean: 0.03
   std: 0.03
- 3sng_fem_dative:
   mean: 0.03
   std: 0.03
- 3sng_fem_poss:
   mean: 0.03
   std: 0.03
- 3sng_fem_poss_det:
   mean: 0.03
   std: 0.03
- 3sng_fem_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_fem_appos_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_fem_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 3plu_subj:
   mean: 0.03
   std: 0.03
- 3plu_pobj:
   mean: 0.03
   std: 0.03
- 3plu_dobj:
   mean: 0.03
   std: 0.03
- 3plu_nsubj_obj:
   mean: 0.03
   std: 0.03
- 3plu_dative:
   mean: 0.03
   std: 0.03
- 3plu_poss:
   mean: 0.03
   std: 0.03
- 3plu_poss_det:
   mean: 0.03
   std: 0.03
- 3sng_neut_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_neut_appos_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_neut_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 3plu_reflexive:
   mean: 0.03
   std: 0.03
- 3plu_appos_reflexive:
   mean: 0.03
   std: 0.03
- 3plu_pobj_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_inan_subj:
   mean: 0.03
   std: 0.03
- 3sng_inan_pobj:
   mean: 0.03
   std: 0.03
- 3sng_inan_dobj:
   mean: 0.03
   std: 0.03
- 3sng_inan_dative:
   mean: 0.03
   std: 0.03
- 3sng_inan_poss:
   mean: 0.03
   std: 0.03
- 3sng_inan_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_inan_appos_reflexive:
   mean: 0.03
   std: 0.03
- 3sng_inan_pobj_reflexive:
   mean: 0.03
   std: 0.03
- int_how:
   mean: 0.05
   std: 0.05
- int_what:
   mean: 0.05
   std: 0.05
- int_whatever:
   mean: 0.02
   std: 0.02
- int_who:
   mean: 0.03
   std: 0.03
- int_whoever:
   mean: 0.02
   std: 0.02
- int_which:
   mean: 0.05
   std: 0.05
- int_whichever:
   mean: 0.02
   std: 0.02
- int_that:
   mean: 0.05
   std: 0.05
- int_whose:
   mean: 0.03
   std: 0.03
- int_when:
   mean: 0.03
   std: 0.03
- int_whenever:
   mean: 0.02
   std: 0.02
- int_where:
   mean: 0.03
   std: 0.03
- int_wherever:
   mean: 0.02
   std: 0.02
- int_whither:
   mean: 0.03
   std: 0.03
- int_whence:
   mean: 0.03
   std: 0.03
- art:
   mean: 0.05
   std: 0.05
- demonstrative:
   mean: 0.05
   std: 0.05
- demonstrative_extra:
   mean: 0.05
   std: 0.05
- det_no:
   mean: 0.03
   std: 0.03
- det_any:
   mean: 0.03
   std: 0.03
- det_some:
   mean: 0.03
   std: 0.03
- det_all:
   mean: 0.03
   std: 0.03
- det_both:
   mean: 0.03
   std: 0.03
- det_each:
   mean: 0.03
   std: 0.03
- det_every:
   mean: 0.03
   std: 0.03
- so:
   mean: 0.03
   std: 0.03
- such:
   mean: 0.03
   std: 0.03
- another:
   mean: 0.03
   std: 0.03
- other:
   mean: 0.03
   std: 0.03
- there:
   mean: 0.03
   std: 0.03
- here:
   mean: 0.03
   std: 0.03
- ins_det:
   mean: 0.05
   std: 0.05
- to:
   mean: 0.05
   std: 0.05
- conj_and:
   mean: 0.05
   std: 0.05
- conj_but:
   mean: 0.05
   std: 0.05
- auxpass:
   mean: 0.03
   std: 0.03
- synonym:
   mean: 0.05
   std: 0.05
- confusion:
   mean: 0.005
   std: 0.005
   model_path: ../../afiksilo/all/afiksilo_dict.pickle
- adj_infl:
   mean: 0.05
   std: 0.05
- noun_infl:
   mean: 0.05
   std: 0.05
- verb_infl:
   mean: 0.1
   std: 0.1
   aux_ratio: 0.20
- part:
   mean: 0.05
   std: 0.05
- del:
   mean: 0.01
   std: 0.01
- an_wo:
   mean: 0.03
   std: 0.03
   ratio: 0.10
- of_wo:
   mean: 0.02
   std: 0.02
- pp_wo:
   mean: 0.02
   std: 0.02
   scale: 1.5
- adv_wo:
   mean: 0.03
   std: 0.03
   scale: 1.5
- wh_wo:
   mean: 0.02
   std: 0.02
   loc: 1.5
   scale: 1.0
- norm_wo:
   mean: 0.3
   std: 0.3
   loc: 0.0
   scale: 0.5
- mask:
   mean: 0.15
   std: 0.15
   p: 0.8
   threshold_mean: 0.20
   threshold_std: 0.20

